---
openapi: 3.0.1
info:
  title: Hommuting API
  version: v1
  description: Korean Real Estate Property Aggregation API
paths:
  "/api/v1/crawling/seoul":
    post:
      summary: 서울 매물 수집
      tags:
      - 크롤링
      description: 서울 전체 25개 구의 매물을 수집합니다. 모든 매물 유형(아파트, 빌라, 오피스텔 등)과 거래 유형(매매, 전세,
        월세)을 포함합니다.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 서울 매물 수집을 시작했습니다
                  collected_count:
                    type: integer
                    example: 150
                  areas:
                    type: array
                    items:
                      type: string
                    example:
                    - 강남구
                    - 강서구
                    - 종로구
                  timestamp:
                    type: string
                    format: date-time
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: 서울 매물 수집 중 오류가 발생했습니다
                  error:
                    type: string
  "/api/v1/crawling/gyeonggi":
    post:
      summary: 경기도 매물 수집
      tags:
      - 크롤링
      description: 경기도 주요 25개 시군의 매물을 수집합니다. 수원, 성남, 고양 등 주요 도시의 모든 매물 유형을 포함합니다.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 경기도 매물 수집을 시작했습니다
                  collected_count:
                    type: integer
                    example: 200
                  areas:
                    type: array
                    items:
                      type: string
                    example:
                    - 수원시
                    - 성남시
                    - 고양시
                  timestamp:
                    type: string
                    format: date-time
  "/api/v1/crawling/all":
    post:
      summary: 전체 매물 수집
      tags:
      - 크롤링
      description: 서울과 경기도 전체 매물을 한 번에 수집합니다. 서울 25개 구와 경기도 25개 시군의 모든 매물을 포함합니다.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 서울 및 경기도 매물 수집을 시작했습니다
                  collected_count:
                    type: integer
                    example: 350
                  areas:
                    type: array
                    items:
                      type: string
                  breakdown:
                    type: object
                    properties:
                      seoul:
                        type: object
                        properties:
                          count:
                            type: integer
                          areas:
                            type: array
                            items:
                              type: string
                      gyeonggi:
                        type: object
                        properties:
                          count:
                            type: integer
                          areas:
                            type: array
                            items:
                              type: string
                  timestamp:
                    type: string
                    format: date-time
  "/api/v1/crawling/status":
    get:
      summary: 크롤링 현황 조회
      tags:
      - 크롤링
      description: 현재 수집된 매물 통계와 크롤링 현황을 조회합니다. 지역별, 매물 유형별, 거래 유형별 분포를 포함합니다.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_properties:
                    type: integer
                    example: 1250
                  seoul_properties:
                    type: integer
                    example: 800
                  gyeonggi_properties:
                    type: integer
                    example: 450
                  by_property_type:
                    type: object
                    example:
                      apartment: 500
                      villa: 300
                      officetel: 250
                  by_deal_type:
                    type: object
                    example:
                      sale: 600
                      jeonse: 400
                      monthly_rent: 250
                  last_updated:
                    type: string
                    format: date-time
                  recent_properties:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        address:
                          type: string
                        property_type:
                          type: string
                        deal_type:
                          type: string
                        created_at:
                          type: string
                          format: date-time
  "/api/v1/properties":
    get:
      summary: 매물 목록 조회
      tags:
      - 매물
      description: 매물 목록을 페이지네이션과 함께 조회합니다. 매물 유형, 거래 유형, 지역 등으로 필터링 가능합니다.
      parameters:
      - name: property_type
        in: query
        enum:
        - apartment
        - villa
        - officetel
        - single_house
        - multi_house
        - mixed_use
        description: "매물 유형 필터:\n * `apartment` \n * `villa` \n * `officetel` \n *
          `single_house` \n * `multi_house` \n * `mixed_use` \n "
        schema:
          type: string
      - name: deal_type
        in: query
        enum:
        - sale
        - jeonse
        - monthly_rent
        description: 거래 유형 필터
        schema:
          type: string
      - name: source
        in: query
        description: 매물 데이터 출처 필터
        schema:
          type: string
      - name: page
        in: query
        description: '페이지 번호 (기본: 1)'
        schema:
          type: integer
      - name: per_page
        in: query
        description: '페이지당 항목 수 (기본: 20)'
        schema:
          type: integer
      - name: lat
        in: query
        description: 중심 위도
        schema:
          type: number
      - name: lng
        in: query
        description: 중심 경도
        schema:
          type: number
      - name: radius
        in: query
        description: 반경 (km)
        schema:
          type: number
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/PropertyList"
  "/api/v1/properties/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: 매물 상세 조회
      tags:
      - 매물
      description: 특정 매물의 상세 정보를 조회합니다.
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
  "/api/v1/properties/search":
    get:
      summary: 매물 검색
      tags:
      - 매물
      description: 제목, 주소, 설명에서 키워드를 검색합니다. 추가 필터링 옵션 사용 가능합니다.
      parameters:
      - name: q
        in: query
        required: true
        description: 검색어
        schema:
          type: string
      - name: property_type
        in: query
        enum:
        - apartment
        - villa
        - officetel
        - single_house
        - multi_house
        - mixed_use
        description: "매물 유형 필터:\n * `apartment` \n * `villa` \n * `officetel` \n *
          `single_house` \n * `multi_house` \n * `mixed_use` \n "
        schema:
          type: string
      - name: deal_type
        in: query
        enum:
        - sale
        - jeonse
        - monthly_rent
        description: 거래 유형 필터
        schema:
          type: string
      - name: source
        in: query
        description: 매물 데이터 출처 필터
        schema:
          type: string
      - name: page
        in: query
        description: '페이지 번호 (기본: 1)'
        schema:
          type: integer
      - name: per_page
        in: query
        description: '페이지당 항목 수 (기본: 20)'
        schema:
          type: integer
      responses:
        '200':
          description: Success
  "/api/v1/properties/stats":
    get:
      summary: 매물 통계
      tags:
      - 매물
      description: 전체 매물 통계 정보를 제공합니다. 총 개수, 유형별 분포, 최근 등록 매물 등을 포함합니다.
      responses:
        '200':
          description: Success
  "/api/v1/properties/by_area":
    get:
      summary: 지역별 매물 조회
      tags:
      - 매물
      description: 특정 좌표 중심으로 반경 내의 매물을 조회합니다. 위도, 경도와 반경을 지정하여 해당 지역의 매물을 검색할 수 있습니다.
      parameters:
      - name: lat
        in: query
        required: true
        description: '중심 위도 (예: 37.5665)'
        schema:
          type: number
      - name: lng
        in: query
        required: true
        description: '중심 경도 (예: 126.9780)'
        schema:
          type: number
      - name: radius
        in: query
        description: '검색 반경 (기본값: 0.01, 약 1km)'
        schema:
          type: number
      - name: property_type
        in: query
        enum:
        - apartment
        - villa
        - officetel
        - single_house
        - multi_house
        - mixed_use
        description: "매물 유형 필터:\n * `apartment` \n * `villa` \n * `officetel` \n *
          `single_house` \n * `multi_house` \n * `mixed_use` \n "
        schema:
          type: string
      - name: deal_type
        in: query
        enum:
        - sale
        - jeonse
        - monthly_rent
        description: 거래 유형 필터
        schema:
          type: string
      - name: source
        in: query
        description: 매물 데이터 출처 필터
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  center:
                    type: object
                    properties:
                      lat:
                        type: number
                      lng:
                        type: number
                  radius:
                    type: number
                  properties:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Property"
                  count:
                    type: integer
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Latitude and longitude are required
components:
  schemas:
    Property:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        address:
          type: string
        price:
          type: string
        property_type:
          type: string
          enum:
          - 아파트
          - 빌라
          - 오피스텔
          - 단독주택
          - 다가구
          - 주상복합
        deal_type:
          type: string
          enum:
          - 매매
          - 전세
          - 월세
        area:
          type: string
        coordinate:
          type: array
          items:
            type: number
        source:
          type: string
    PropertyList:
      type: object
      properties:
        properties:
          type: array
          items:
            "$ref": "#/components/schemas/Property"
        pagination:
          "$ref": "#/components/schemas/Pagination"
    Pagination:
      type: object
      properties:
        current_page:
          type: integer
        per_page:
          type: integer
        total_count:
          type: integer
servers:
- url: http://localhost:3000
  description: Development server
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: api.hommuting.com
  description: Production server
