---
openapi: 3.0.1
info:
  title: Hommuting Crawling API V1
  version: v1
  description: 한국 부동산 매물 수집 API - 직방 등 부동산 사이트에서 매물 데이터를 수집하는 크롤링 시스템
paths:
  "/api/v1/crawling/seoul":
    post:
      summary: 서울 지역 매물 수집 (Geohash 기반)
      tags:
      - 크롤링 API
      description: |
        서울 지역의 부동산 매물을 geohash 기반 스트리밍 방식으로 수집합니다.

        **스트리밍 크롤링 시스템:**
        1. **ID 수집**: 각 geohash 영역별로 매물 ID를 수집 (GET 요청)
        2. **상세 정보**: 수집된 ID를 15개씩 배치로 나누어 상세 정보 조회 (POST 요청)
        3. **즉시 저장**: 각 geohash별로 독립 트랜잭션으로 DB 저장

        **개발 모드**: 1개 geohash만 테스트 수집 (wydm5)
        **전체 모드**: 서울 전체 geohash 영역 수집 (약 96개 영역, 스트리밍 처리)

        **장점**: 메모리 효율성, 실패 시 부분 복구 가능, 실시간 진행상황 확인
      parameters:
      - name: dev_mode
        in: query
        description: '개발 모드 (true: 제한된 geohash만 테스트, false: 전체 수집)'
        schema:
          type: boolean
      - name: property_types
        in: query
        items:
          type: string
          enum:
          - oneroom
          - villa
          - officetel
        description: '수집할 매물 유형 (기본값: oneroom, villa, officetel 전체)'
        schema:
          type: array
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 서울 전체 매물 수집 완료
                  collected_count:
                    type: integer
                    example: 1250
                  successful_geohashes:
                    type: integer
                    example: 94
                    description: 성공적으로 처리된 geohash 수
                  failed_geohashes:
                    type: integer
                    example: 2
                    description: 실패한 geohash 수
                  property_types:
                    type: object
                    properties:
                      원룸:
                        type: integer
                        example: 800
                      빌라:
                        type: integer
                        example: 300
                      오피스텔:
                        type: integer
                        example: 150
                  sample_properties:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        address_text:
                          type: string
                        price:
                          type: string
                        property_type:
                          type: string
                        deal_type:
                          type: string
                        area_sqm:
                          type: number
                        current_floor:
                          type: integer
                          description: 현재 층
                        total_floors:
                          type: integer
                          description: 총 층수
                        room_structure:
                          type: string
                          example: '01'
                          description: 방 구조 코드 (01:오픈형원룸, 04:투룸, 05:쓰리룸)
                        maintenance_fee:
                          type: integer
                          description: 관리비 (원)
                        thumbnail_url:
                          type: string
                          description: 썸네일 이미지 URL
                        source:
                          type: string
                          example: zigbang_api
                        external_id:
                          type: string
                  geohash_count:
                    type: integer
                    example: 96
                  dev_mode:
                    type: boolean
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                  error:
                    type: string
  "/api/v1/crawling/gyeonggi":
    post:
      summary: 경기도 지역 매물 수집 (Geohash 기반)
      tags:
      - 크롤링 API
      description: |
        경기도 지역의 부동산 매물을 geohash 기반으로 수집합니다.

        서울과 동일한 2단계 크롤링 시스템을 사용하며,
        경기도 전체 geohash 영역 (약 96개)에서 매물을 수집합니다.
      parameters:
      - name: dev_mode
        in: query
        description: 개발 모드
        schema:
          type: boolean
      - name: property_types
        in: query
        items:
          type: string
          enum:
          - oneroom
          - villa
          - officetel
        description: '수집할 매물 유형 (기본값: oneroom, villa, officetel 전체)'
        schema:
          type: array
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/CrawlingResponse"
  "/api/v1/crawling/all":
    post:
      summary: 서울+경기도 전체 매물 수집
      tags:
      - 크롤링 API
      description: |
        서울과 경기도 전체 지역의 부동산 매물을 수집합니다.

        **처리 순서:**
        1. 서울 지역 전체 geohash 수집
        2. 10초 대기 (안티 봇)
        3. 경기도 지역 전체 geohash 수집

        **예상 소요 시간**: 전체 모드 시 수 시간 소요 가능
      parameters:
      - name: dev_mode
        in: query
        description: 개발 모드
        schema:
          type: boolean
      - name: property_types
        in: query
        items:
          type: string
          enum:
          - oneroom
          - villa
          - officetel
        description: '수집할 매물 유형 (기본값: oneroom, villa, officetel 전체)'
        schema:
          type: array
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  total_collected:
                    type: integer
                  breakdown:
                    type: object
                    properties:
                      seoul:
                        type: object
                        properties:
                          count:
                            type: integer
                          geohash_count:
                            type: integer
                          property_types:
                            type: object
                          sample_properties:
                            type: array
                      gyeonggi:
                        type: object
                        properties:
                          count:
                            type: integer
                          geohash_count:
                            type: integer
                          property_types:
                            type: object
                          sample_properties:
                            type: array
                  dev_mode:
                    type: boolean
                  timestamp:
                    type: string
components:
  schemas:
    CrawlingResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: 경기도 전체 매물 수집 완료
        collected_count:
          type: integer
          example: 1100
        successful_geohashes:
          type: integer
          example: 96
          description: 성공적으로 처리된 geohash 수
        failed_geohashes:
          type: integer
          example: 0
          description: 실패한 geohash 수
        property_types:
          type: object
          properties:
            원룸:
              type: integer
              example: 700
            빌라:
              type: integer
              example: 250
            오피스텔:
              type: integer
              example: 150
        sample_properties:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              title:
                type: string
              address_text:
                type: string
              price:
                type: string
              property_type:
                type: string
              deal_type:
                type: string
              area_sqm:
                type: number
              current_floor:
                type: integer
                description: 현재 층
              total_floors:
                type: integer
                description: 총 층수
              room_structure:
                type: string
                example: '01'
                description: 방 구조 코드 (01:오픈형원룸, 04:투룸, 05:쓰리룸)
              maintenance_fee:
                type: integer
                description: 관리비 (원)
              thumbnail_url:
                type: string
                description: 썸네일 이미지 URL
              source:
                type: string
                example: zigbang_api
              external_id:
                type: string
        geohash_count:
          type: integer
          example: 96
        dev_mode:
          type: boolean
        timestamp:
          type: string
servers:
- url: http://localhost:3000
  description: Development server
- url: https://crawling.hommuting.com
  description: Production crawling server
