---
openapi: 3.0.1
info:
  title: Hommuting API
  version: v1
  description: Korean Real Estate Property Aggregation API
paths:
  "/api/v1/properties":
    get:
      summary: 매물 목록 조회
      tags:
      - 매물
      description: 매물 목록을 페이지네이션과 함께 조회합니다. 매물 유형, 거래 유형, 지역 등으로 필터링 가능합니다.
      parameters:
      - name: property_type
        in: query
        enum:
        - apartment
        - villa
        - officetel
        - single_house
        - multi_house
        - mixed_use
        description: "매물 유형 필터:\n * `apartment` \n * `villa` \n * `officetel` \n *
          `single_house` \n * `multi_house` \n * `mixed_use` \n "
        schema:
          type: string
      - name: deal_type
        in: query
        enum:
        - sale
        - jeonse
        - monthly_rent
        description: 거래 유형 필터
        schema:
          type: string
      - name: source
        in: query
        description: 매물 데이터 출처 필터
        schema:
          type: string
      - name: page
        in: query
        description: '페이지 번호 (기본: 1)'
        schema:
          type: integer
      - name: per_page
        in: query
        description: '페이지당 항목 수 (기본: 20)'
        schema:
          type: integer
      - name: lat
        in: query
        description: 중심 위도
        schema:
          type: number
      - name: lng
        in: query
        description: 중심 경도
        schema:
          type: number
      - name: radius
        in: query
        description: 반경 (km)
        schema:
          type: number
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/PropertyList"
  "/api/v1/properties/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: 매물 상세 조회
      tags:
      - 매물
      description: 특정 매물의 상세 정보를 조회합니다.
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
  "/api/v1/properties/search":
    get:
      summary: 매물 검색
      tags:
      - 매물
      description: 제목, 주소, 설명에서 키워드를 검색합니다. 추가 필터링 옵션 사용 가능합니다.
      parameters:
      - name: q
        in: query
        required: true
        description: 검색어
        schema:
          type: string
      - name: property_type
        in: query
        enum:
        - apartment
        - villa
        - officetel
        - single_house
        - multi_house
        - mixed_use
        description: "매물 유형 필터:\n * `apartment` \n * `villa` \n * `officetel` \n *
          `single_house` \n * `multi_house` \n * `mixed_use` \n "
        schema:
          type: string
      - name: deal_type
        in: query
        enum:
        - sale
        - jeonse
        - monthly_rent
        description: 거래 유형 필터
        schema:
          type: string
      - name: source
        in: query
        description: 매물 데이터 출처 필터
        schema:
          type: string
      - name: page
        in: query
        description: '페이지 번호 (기본: 1)'
        schema:
          type: integer
      - name: per_page
        in: query
        description: '페이지당 항목 수 (기본: 20)'
        schema:
          type: integer
      responses:
        '200':
          description: Success
  "/api/v1/properties/stats":
    get:
      summary: 매물 통계
      tags:
      - 매물
      description: 전체 매물 통계 정보를 제공합니다. 총 개수, 유형별 분포, 최근 등록 매물 등을 포함합니다.
      responses:
        '200':
          description: Success
components:
  schemas:
    Property:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        address:
          type: string
        price:
          type: string
        property_type:
          type: string
          enum:
          - 아파트
          - 빌라
          - 오피스텔
          - 단독주택
          - 다가구
          - 주상복합
        deal_type:
          type: string
          enum:
          - 매매
          - 전세
          - 월세
        area:
          type: string
        coordinate:
          type: array
          items:
            type: number
        source:
          type: string
    PropertyList:
      type: object
      properties:
        properties:
          type: array
          items:
            "$ref": "#/components/schemas/Property"
        pagination:
          "$ref": "#/components/schemas/Pagination"
    Pagination:
      type: object
      properties:
        current_page:
          type: integer
        per_page:
          type: integer
        total_count:
          type: integer
servers:
- url: http://localhost:3000
  description: Development server
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: api.hommuting.com
  description: Production server
